### PR TITLE
DTSCI-97 ReadMe Badges (Coverage, Build Status, etc)

### PR DESCRIPTION
**Pull request by CurtisUnderwood**
### Description 
Readme badges for Build Status, Jest Coverage, and Dependency versions. Generates dynamic readme badges using JSON endpoints from gh-pages. 

List of proposed changes:

- Added ReadMe Badges for build status, Jest coverage, and dependency versions.
- Badges update automatically whenever a branch is merged with main. 

### What to test for/How to test
- See badges in README.md

### Additional Notes
- Fixed issue with Automatic URL Commenting where URL would include nonexistent directory

### CODE REVIEW

**Review by shewood — COMMENTED** [review]
I am wondering about the coverage-summary.json. it looks like this is not a file we want checked into the repo?

**Comment by CurtisUnderwood** [comment]
> I am wondering about the coverage-summary.json. it looks like this is not a file we want checked into the repo?

Hey Sheila, the ReadMe badge for coverage needs to pull the coverage summary data from somewhere since it's usually in the /coverage file and gitignored, if it's left in there the badge won't be able to display any data once it's pushed to GitHub. Alternatively, it can pull the data from gh-pages since the /coverage dir is deployed there whenever a PR is merged with the main branch, however, the old test coverage script wasn't generating the summary file so it was never deployed. We can either wait until a branch deploys to gh-pages with coverage-summary and fix the badge to request the data from there or forgo the coverage badge if coverage-summary isn't a good idea to keep in the repo. Let me know what the best direction here may be.

**Comment by shewood** [comment]
I am getting a 404 from all of the link above.

**Review by P0NDER0SA — APPROVED** [review]
Really nice work @CurtisUnderwood love how the readme looks now

**Pull request merged**
